name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  generate_snapshots:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: Install dependencies
      working-directory: HtmlGenerator
      run: npm install

    - name: Install fonts
      run: sudo apt-get install -y fonts-inter

    - name: Install Playwright browsers
      working-directory: HtmlGenerator
      run: npx playwright install --with-deps chromium

    - name: Generate HTML
      working-directory: HtmlGenerator
      run: pwsh ./generate_web.ps1

    - name: Generate snapshots
      working-directory: HtmlGenerator
      run: node song_display_test.js --update

    - name: Upload snapshots
      uses: actions/upload-artifact@v6
      with:
        name: snapshots
        path: HtmlGenerator/snapshots/
